apps/collectors/urls.py
from django.urls import path
from .views import CollectorInformation, ViewCollectorForm, AddCollectorForm, UpdateCollectorForm, collector_page, add_collector, update_collector

app_name = "collectors"

urlpatterns = [
    path("collectors/", CollectorInformation.as_view(), name="collectors"),
    path("view-collector/<int:pk>/", ViewCollectorForm.as_view(), name="view-collector"),
    path(
        "add-collector-form/",
        AddCollectorForm.as_view(),
        name="add-collector-form",
    ),
    path(
        "update-collector-form/<int:pk>/",
        UpdateCollectorForm.as_view(),
        name="update-collector-form",
    ),
]


htmx_urlpatterns = [
    path("collector-page/<int:page>", collector_page, name="page-collector"),
    
    path("add-collector/", add_collector, name="add-collector"),
    path(
        "update-collector/<int:pk>/", update_collector, name="update-collector"
    ),
]

urlpatterns += htmx_urlpatterns

config/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import include, path, re_path
from django.views.static import serve
from drf_spectacular.views import (
    SpectacularAPIView,
    SpectacularRedocView,
    SpectacularSwaggerView,
)

schema_urls = [
    # YOUR PATTERNS
    path("api/v1/schema/", SpectacularAPIView.as_view(), name="schema"),
    # Optional UI:
    path(
        "api/v1/schema/swagger/",
        SpectacularSwaggerView.as_view(url_name="schema"),
        name="swagger",
    ),
    path(
        "api/v1/schema/redoc/",
        SpectacularRedocView.as_view(url_name="schema"),
        name="redoc",
    ),
]

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("apps.common.urls")),
    path("", include("apps.dashboard.urls")),
    path("", include("apps.users.urls")),
    path("", include("apps.clients.urls")),
    path("", include("apps.loans.urls")),
    path("", include("apps.transactions.urls")),
    path("", include("apps.ledger_accounts.urls")),
    path("", include("apps.collectors.urls")),
    re_path(r"^media/(?P<path>.*)$", serve, {"document_root": settings.MEDIA_ROOT}),
]

urlpatterns += schema_urls
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [
        path("__debug__/", include(debug_toolbar.urls)),
    ]

apps/collectors/models.py
from django.db import models


# Create your models here.
class TimeStampedModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class Collector(TimeStampedModel):
    full_name = models.CharField(max_length=150)
    contact_no = models.CharField(max_length=50, blank=True)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.full_name

apps/collectors/forms.py
from django import forms
from .models import Collector
from dynamic_forms import DynamicFormMixin


class CollectorForm(DynamicFormMixin, forms.ModelForm):
    class Meta:
        model = Collector
        fields = (
            "full_name",
            "contact_no",
            "is_active",
        )

apps/collectors/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.list import ListView
from django.conf import settings
from .models import Collector
from django.db.models.functions import Concat
from django.db.models import Value
from django.core.paginator import Paginator
from .forms import CollectorForm
from django.contrib import messages
from django.views.generic import FormView


# Create your views here.
class CollectorInformation(LoginRequiredMixin, ListView):
    template_name = "collector/collectors.html"
    model = Collector

    paginate_by = settings.PAGINATE_BY  # set number of records per page


class ViewCollectorForm(LoginRequiredMixin, FormView):
    def get(self, request, pk):
        print("view collector details")
        collector = Collector.objects.get(pk=pk)
        form = CollectorForm(request.POST or None, instance=collector)

        context = {
            "collector": collector,
            "forms": form,
        }

        return render(request, "collector/partials/collector-view.html", context)



class AddCollectorForm(LoginRequiredMixin, ListView):
    def get(self, request):
        print("collector add page")
        collector = {"is_active": True}
        form = CollectorForm(request.POST or None)
        context = {"form": form, "collector": collector}
        return render(request, "collector/partials/collector-add-form.html", context)


class UpdateCollectorForm(LoginRequiredMixin, FormView):
    def get(self, request, pk):
        print("load collector update page")
        collector = Collector.objects.get(pk=pk)
        form = CollectorForm(request.POST or None, instance=collector)

        collector = get_object_or_404(Collector, pk=pk)
        context = {"collector": collector, "form": form}

        return render(request, "collector/partials/collector-update-form.html", context)


def collector_page(request, page):
    print("get page")
    search_text = request.POST.get("search-collector")
    collectors = Collector.objects.filter(full_name__icontains=search_text).order_by(
        "-created_at"
    )

    # setup pagination
    p = Paginator(collectors, settings.PAGINATE_BY)
    collectors = p.get_page(page)

    total_records = p.count  # count total records

    context = {"collectors": collectors, "total_records": total_records}
    return render(request, "collector/partials/collector-list-elements.html", context)


def add_collector(request):
    print("add collector")
    form = CollectorForm(request.POST or None)

    if form.is_valid():
        form.save()

        collectors = Collector.objects.all()
        total_records = collectors.count()  # count total records

        messages.success(request, "Record added...")
        context = {"collectors": collectors, "total_records": total_records}
        return render(request, "collector/partials/collector-list.html", context)
    form = CollectorForm(request.POST or None)
    context = {"forms": form}
    return render(request, "collector/partials/collector-add-form.html", context)


def update_collector(request, pk):
    print("update collector")
    collector = Collector.objects.get(pk=pk)
    form = CollectorForm(request.POST, request.FILES or None, instance=collector)
    if form.is_valid():
        form.save()
        context = {"forms": form, "collector": collector}
        messages.success(request, "Record updated...")
        return render(request, "collector/partials/collector-view-details.html", context)
    form = CollectorForm(request.POST or None, instance=collector)
    context = {"forms": form}
    return render(request, "collector/partials/collector-update-form.html", context)

templates/collector/partials/collector-add-form.html
<form hx-encoding="multipart/form-data"
        hx-post="{% url 'collectors:add-collector' %}"
        hx-target="#collector"
        >
    {% csrf_token %}
    {% include 'collector/partials/collector-fields.html' %}
</form>

templates/collector/partials/collector-button-page.html
<nav class="flex items-center justify-between bg-white py-3" aria-label="Pagination">
    <div class="pagination gap-x-3">
        {% if collectors.has_previous %}
            <button hx-post="{% url 'collectors:page-collector' 1 %}"
                    hx-target="#collector-list"
                    class="relative inline-flex items-center rounded-md bg-white px-3 py-2 text-sm font-semibold text-gray-900 ring-1 ring-inset ring-gray-300 hover:bg-gray-50 focus-visible:outline-offset-0">
                first
            </button>
        {% else %}
            <span disable
                    class="relative inline-flex items-center rounded-md bg-gray px-3 py-2 text-sm font-semibold text-gray-900 ring-1 ring-inset ring-gray-300 hover:bg-gray-50 focus-visible:outline-offset-0">
                first
            </span>
        {% endif %}

        {% if collectors.has_previous %}
            <button hx-post="{% url 'collectors:page-collector'  collectors.previous_page_number  %}"
                    hx-target="#collector-list"
                    class="relative inline-flex items-center rounded-md bg-white px-3 py-2 text-sm font-semibold text-gray-900 ring-1 ring-inset ring-gray-300 hover:bg-gray-50 focus-visible:outline-offset-0">
                previous
            </button>
        {% else %}
            <span disabled
                    class="relative inline-flex items-center rounded-md bg-white px-3 py-2 text-sm font-semibold text-gray-900 ring-1 ring-inset ring-gray-300 hover:bg-gray-50 focus-visible:outline-offset-0">
                previous
            </span>
        {% endif %}

        {% if collectors.has_next %}
            <button hx-post="{% url 'collectors:page-collector'  collectors.next_page_number  %}"
                    hx-target="#collector-list"
                    class="relative inline-flex items-center rounded-md bg-white px-3 py-2 text-sm font-semibold text-gray-900 ring-1 ring-inset ring-gray-300 hover:bg-gray-50 focus-visible:outline-offset-0">
                next
            </button>

        {% else %}
            <span disabled
                    class="relative inline-flex items-center rounded-md bg-white px-3 py-2 text-sm font-semibold text-gray-900 ring-1 ring-inset ring-gray-300 hover:bg-gray-50 focus-visible:outline-offset-0">
                next
            </span>
        {% endif %}

        {% if collectors.has_next %}
            <button hx-post="{% url 'collectors:page-collector'  collectors.paginator.num_pages  %}"
                    hx-target="#collector-list"
                    class="relative inline-flex items-center rounded-md bg-white px-3 py-2 text-sm font-semibold text-gray-900 ring-1 ring-inset ring-gray-300 hover:bg-gray-50 focus-visible:outline-offset-0">
                last
            </button>
        {% else %}
            <span disabled
                    class="relative inline-flex items-center rounded-md bg-white px-3 py-2 text-sm font-semibold text-gray-900 ring-1 ring-inset ring-gray-300 hover:bg-gray-50 focus-visible:outline-offset-0">
                last
            </span>
        {% endif %}
    </div>

    <div class="flex flex-1 justify-between sm:justify-end mr-4">
        <p class="text-sm text-gray-700">
        <span class="font-medium">{{ total_records }}</span>
        records found
        </p>
    </div>
</nav>

<div class="hidden sm:block">
    <span class="current">
      Page {{ collectors.number }} of {{ collectors.paginator.num_pages }}.
    </span>
</div>

templates/collector/partials/collector-fields.html
{% load widget_tweaks %}

<div class="grid grid-cols-1 border-b border-gray-900/10 pb-12 md:grid-cols-2 flex items-center justify-end gap-x-6 border-t border-gray-900/10  py-4 bg-gray-50 text-white py-4 px-6 sticky top-0 z-50">
    <div>
      <h2 class="text-base font-semibold leading-7 text-gray-900">
        {% if form.full_name.value %}
          {{ collector.full_name }}
        {% else %}
          New Collector
        {% endif %}
      </h2>
    </div>
    
    <div class="text-right inline-flow">
      <span class="p-4">
        <a href="{% url 'collectors:collectors' %}" class="text-sm font-semibold leading-6 text-gray-900">Cancel</a>
      </span>
      <button type="submit"
              class="rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600"
      >Proceed</button>
    </div>
   
</div>

<div class="grid grid-cols-1 gap-y-10 pb-4 md:grid-cols-4">
    <div class="grid max-w-2xl grid-cols-1 gap-x-6 gap-y-8 sm:grid-cols-6 md:col-span-2 pt-5">

        <div class="sm:col-span-4">
            <label for="loan" class="block text-sm font-medium leading-6 text-gray-900">Fullname</label>
            <div class="mt-2">
              {%  render_field form.full_name class="px-2 bg-white block rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:max-w-xs sm:text-sm sm:leading-6" %}
            </div>
        </div>

        <div class="col-span-full">
            <label for="payment_method" class="block text-sm font-medium leading-6 text-gray-900">Contact No.</label>
            <div class="mt-2">
                {% render_field form.contact_no class="px-2 bg-white block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6" %}
            </div>
        </div>

    <div x-data="{ open: {{ collector.is_active|yesno:"true,false" }} }" class="sm:col-span-1">
      <label for="status" class="block text-sm font-medium leading-6 text-gray-900">Status</label>
      
      <input type="text" name="status" :value="open" hidden>
      <button x-on:click="open = ! open" 
              type="button" 
              :class="[open ? 'bg-indigo-600': 'bg-gray-200' , 'relative inline-flex h-6 w-11 flex-shrink-0 cursor-pointer rounded-full border-2 border-transparent transition-colors duration-200 ease-in-out focus:outline-none focus:ring-2 focus:ring-indigo-600 focus:ring-offset-2']" role="switch" aria-checked="false" aria-labelledby="availability-label" aria-describedby="availability-description">
          <span aria-hidden="True" 
              :class="[open ? 'translate-x-5': 'translate-x-0' ,  'pointer-events-none inline-block h-5 w-5 transform rounded-full bg-white shadow ring-0 transition duration-200 ease-in-out']"></span>
      </button>
    </div>
  </div>
</div>

templates/collector/partials/collector-list-elements.html
{% include 'collector/partials/collector-button-page.html' %}

<div class="mt-4 flow-root">
    <div class="-mx-4 -my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
      <div class="inline-block min-w-full py-2 align-middle sm:px-6 lg:px-8">
        <div id="no-more-tables" class="overflow-hidden shadow ring-1 ring-black ring-opacity-5 sm:rounded-lg">
          <table class="min-w-full divide-y divide-gray-300">
              <thead class="bg-gray-50">
                <tr>
                  <th scope="col" class="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-6">Fullname</th>
                  <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Contact Number</th>
                  <th scope="col" class="relative py-3.5 pl-3 pr-4 sm:pr-6">
                  <span class="sr-only">Edit</span>
                  </th>
                </tr>
              </thead>
            <tbody class="divide-y divide-gray-200 bg-white" >
               
            {% for collector in collectors %}
            <tr>
                <td data-title="Name" class="whitespace-nowrap py-4 pl-4 pr-3 text-sm font-medium text-gray-900 sm:pl-6">{{ collector.full_name }}</td>
                <td data-title="Email" class="whitespace-nowrap px-3 py-4 text-sm text-gray-500">{{ collector.contact_no }}</td>
                <td class="relative whitespace-nowrap py-4 pl-3 pr-4 text-right text-sm font-medium sm:pr-6">
                    <a href="{% url 'collectors:view-collector' collector.pk %}" class="text-indigo-600 hover:text-indigo-900">View</a>
                </td>
            </tr>
            {% endfor %}
            
            </tbody>
           
          </table>
          {% if not collectors %}
            <p class="p-2 text-center">no records found</p>
          {% endif %}
        </div>
      </div>
    </div>
</div>

templates/collector/partials/collector-list.html
{% if messages %}
    {% for message in messages %}
        <div class="alert alert-warning alert-dismissible fade show" role="alert">{{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    {% endfor %}
{% endif %}

<form  hx-triggger="end" hx-target="#collector-result" >
    {% include 'collector/partials/search.html' %}
    <div id="collector-list" hx-post="{% url 'collectors:page-collector' 1  %}" hx-trigger="revealed" hx-target="this">

    </div>
</form>

templates/collector/partials/collector-update-form.html
<form hx-encoding="multipart/form-data"
        hx-post="{% url 'collectors:update-collector' collector.pk %}"
        hx-target="#collector-view">
    {% csrf_token %}
    {% include 'collector/partials/collector-fields.html' %}
</form>

templates/collector/partials/collector-view-details.html
{% load static %}
{% load widget_tweaks %}

{% if messages %}
{% for message in messages %}
    <div class="alert alert-warning alert-dismissible fade show" role="alert">{{ message }}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
{% endfor %}
{% endif %}

<div class="grid grid-cols-1 border-b border-gray-900/10 pb-12 md:grid-cols-2 flex items-center justify-end gap-x-6 border-t border-gray-900/10  py-3 bg-gray-50 text-white py-4 px-6 sticky top-0 z-50 mb-5">
  <div>
    <h2 class="text-base font-semibold leading-7 text-gray-900">{{ collector.full_name }}</h2>
  </div>
  
  <div class="text-right inline-flow">
    <span class="p-4">
      <a href="{% url 'collectors:collectors' %}" class="text-sm font-semibold leading-6 text-gray-900">Back</a>
    </span>

    <button hx-get="{% url 'collectors:update-collector-form' collector.pk %}" hx-target="#collector-view"
            type="button"
            class="rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600"
    >Update</button>

  </div>
</div>

<div class="overflow-hidden bg-white shadow sm:rounded-lg">
  <div class="px-4 py-6 sm:px-6">
    <h3 class="text-base font-semibold leading-7 text-gray-900">Collector details.</h3>
  </div>
  <div class="border-t border-gray-100">
    <dl class="divide-y divide-gray-100">
      <div class="px-4 py-6 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
        <dt class="text-sm font-semibold text-gray-900">Full name</dt>
        <dd class="mt-1 text-sm leading-6 text-gray-700 sm:col-span-2 sm:mt-0">{{ collector.full_name }}</dd>
      </div>
      <div class="px-4 py-6 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
        <dt class="text-sm font-semibold text-gray-900">Contact No.</dt>
        <dd class="mt-1 text-sm leading-6 text-gray-700 sm:col-span-2 sm:mt-0">{{ collector.contact_no }}</dd>
      </div>
      <div class="px-4 py-6 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
        <dt class="text-sm font-semibold text-gray-900">Status</dt>
        <dd class="mt-1 text-sm leading-6 text-gray-700 sm:col-span-2 sm:mt-0">
          {% if forms.is_active.value %}
          <div class="flex items-start gap-x-3">
            <div class="rounded-md py-1 px-2 text-xs font-medium ring-1 ring-inset text-green-700 bg-green-50 ring-green-600/20">Active</div>
          </div>
          {% else %}
          <div class="flex items-start gap-x-3">
            <div class="rounded-md py-1 px-2 text-xs font-medium ring-1 ring-inset text-green-700 bg-green-50 ring-green-600/20">Inactive</div>
          </div>
          {% endif %} 
          
        </dd>
      </div>
      
    </dl>
  </div>
</div>

templates/collector/partials/collector-view.html
{% extends 'base.html' %}
{% block content %}

{% load static %}
{% load widget_tweaks %}

<section id="collector-view" class="col-12">
  {% include 'collector/partials/collector-view-details.html' %}
</section>
{% endblock content %}

templates/collector/partials/search.html
<div class="sm:col-span-4">
    <label for="search-collector" class="block text-sm font-medium leading-6 text-gray-900">Search</label>
        <div class="mt-2">
            <input hx-post="{% url 'collectors:page-collector' 1 %}"
                   hx-target="#collector-list"
                   hx-replace-url="false"
                   hx-trigger="keyup changed delay:500ms load"
                   type="text"
                   name="search-collector"
                   id="search-collector"
                   placeholder="Search"
                   class="px-2 w-1/2 block rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6">
        </div>
</div>