apps/dashboard/urls.py
from django.urls import path
from .views import DashboardView, donut_chart_statistic, bar_chart_statistic, recent_loan_activity, recent_payment_activity, recent_client

app_name = "dashboard"

urlpatterns = [
    path("", DashboardView.as_view(), name="dashboard"),
    path("dashboard/", DashboardView.as_view(), name="dashboard"),
]


htmx_urlpatterns = [
    path("donut-chart/", donut_chart_statistic, name="donut-chart"),
    path("bar-chart/", bar_chart_statistic, name="bar-chart"),
    path("recent-loan/", recent_loan_activity, name="recent-loan"),
    path("recent-payment/", recent_payment_activity, name="recent-payment"),
    path("recent-client/", recent_client, name="recent-client"),
]

urlpatterns += htmx_urlpatterns

config/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import include, path, re_path
from django.views.static import serve
from drf_spectacular.views import (
    SpectacularAPIView,
    SpectacularRedocView,
    SpectacularSwaggerView,
)

schema_urls = [
    # YOUR PATTERNS
    path("api/v1/schema/", SpectacularAPIView.as_view(), name="schema"),
    # Optional UI:
    path(
        "api/v1/schema/swagger/",
        SpectacularSwaggerView.as_view(url_name="schema"),
        name="swagger",
    ),
    path(
        "api/v1/schema/redoc/",
        SpectacularRedocView.as_view(url_name="schema"),
        name="redoc",
    ),
]

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("apps.common.urls")),
    path("", include("apps.dashboard.urls")),
    path("", include("apps.users.urls")),
    path("", include("apps.clients.urls")),
    path("", include("apps.loans.urls")),
    path("", include("apps.transactions.urls")),
    path("", include("apps.ledger_accounts.urls")),
    path("", include("apps.collectors.urls")),
    re_path(r"^media/(?P<path>.*)$", serve, {"document_root": settings.MEDIA_ROOT}),
]

urlpatterns += schema_urls
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [
        path("__debug__/", include(debug_toolbar.urls)),
    ]

apps/dashboard/models.py
from django.db import models

# Create your models here.

apps/loans/models.py
import uuid
from django.db import models
from datetime import datetime
from dateutil.relativedelta import relativedelta
from apps.clients.models import Client
from apps.transactions.models import Transaction, TransactionEntry
from apps.ledger_accounts.models import LedgerAccount
from .utils import (
    calculate_loan_interest,
    calculate_loan_payment,
)

# Create your models here.

class TimeStampedModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class LoanProduct(TimeStampedModel):
    loan_product = models.CharField(max_length=150, unique=True)
    description = models.TextField(null=True, blank=True)
    penalty = models.IntegerField(null=True, blank=True)

    ledger_account = models.ForeignKey(
        LedgerAccount, on_delete=models.CASCADE, null=True
    )
    status = models.BooleanField(default=True)

    def save(self, *args, **kwargs):
        if not self.ledger_account:
            ledger_account = LedgerAccount.objects.create(
                ledger_type="assets",
                account_title=self.loan_product,
            )
            self.ledger_account = ledger_account

        super().save(*args, **kwargs)

    def __str__(self):
        return self.loan_product


class LoanTerm(TimeStampedModel):
    class TermsMonths(models.TextChoices):
        terms_60 = 60, "60"
        terms_48 = 48, "48"
        terms_36 = 36, "36"
        terms_24 = 24, "24"
        terms_18 = 18, "18"
        terms_12 = 12, "12"
        terms_6 = 6, "6"
        terms_3 = 3, "3"

    loan_product = models.ForeignKey(
        LoanProduct, on_delete=models.CASCADE, related_name="loan_product_terms"
    )
    terms = models.IntegerField(
        choices=TermsMonths.choices
    )
    interest_rate = models.DecimalField(max_digits=5, decimal_places=2)
    ledger_account = models.ForeignKey(
        LedgerAccount, on_delete=models.CASCADE, null=True
    )
    status = models.BooleanField(default=True)

    def save(self, *args, **kwargs):
        print("Loan terms")
        if not self.ledger_account:
            ledger_account = LedgerAccount.objects.create(
                ledger_type="income",
                account_title="Interest - " + self.loan_product,
            )

            self.ledger_account = ledger_account
        super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.loan_product} - Months {self.terms} - Interest rate {self.interest_rate}%"


class Loan(TimeStampedModel):
    class LoanStatus(models.TextChoices):
        pending = "pending", "Pending"
        approved = "approved", "Approved"
        cancelled = "cancelled", "Cancelled"
        released = "released", "Released"
        fully_paid = "fully_paid", "Fully Paid"

    transaction = models.OneToOneField(
        Transaction, null=True, blank=True, on_delete=models.CASCADE
    )
    client = models.ForeignKey(Client, null=True, on_delete=models.CASCADE)
    loan_number = models.CharField(max_length=12, editable=False, unique=True)
    loan_product = models.ForeignKey(LoanProduct, on_delete=models.CASCADE, null=True)
    loan_amount = models.DecimalField(max_digits=10, decimal_places=2)
    monthly_payment = models.DecimalField(max_digits=10, null=True, decimal_places=2)
    terms = models.ForeignKey(LoanTerm, null=True, on_delete=models.CASCADE)
    loan_terms = models.IntegerField(null=True)
    interest_rate = models.DecimalField(max_digits=5, decimal_places=2)
    interest_amount = models.DecimalField(
        max_digits=10, null=True, blank=True, decimal_places=2
    )
    approval_date = models.DateField(null=True, blank=True)
    release_date = models.DateField(null=True, blank=True)
    maturity_date = models.DateField(null=True, blank=True)
    status = models.CharField(
        max_length=25, choices=LoanStatus.choices, default=LoanStatus.pending
    )
    cancelled_date = models.DateField(null=True, blank=True)
    fully_paid_date = models.DateTimeField(null=True)

    @property
    def total_paid_interest(self):
        total = 0
        payments = Payment.objects.filter(loan=self.id).select_related("transaction")
        for p in payments:
            transaction_entry = TransactionEntry.objects.filter(
                transaction=p.transaction.id,
                entry_type="d",
                ledger_account=self.terms.ledger_account,
            )
            
            if transaction_entry:
                total += transaction_entry[0].amount

        return total

    @property
    def total_paid_principal(self):
        total = 0
        payments = Payment.objects.filter(loan=self.id).select_related("transaction")
        for p in payments:
            transaction_entry = TransactionEntry.objects.filter(
                transaction=p.transaction.id,
                entry_type="d",
                ledger_account=self.loan_product.ledger_account,
            )
            if transaction_entry:
                total += transaction_entry[0].amount

        return total

    @property
    def remaining_principal_balance(self):
        return self.loan_amount - self.total_paid_principal

    @property
    def remaining_interest_balance(self):
        return self.interest_amount - self.total_paid_interest

    def create_update_transaction(self):
        transaction_type = "cv"

        # create a transaction for loan
        transaction = Transaction.objects.create(
            transaction_no=self.transaction, transaction_type=transaction_type
        )

        self.transaction = transaction

        # create transaction entry for debit, credit, and cash disbursement
        TransactionEntry.objects.update_or_create(
            transaction=transaction,
            entry_type="d",
            defaults={
                "ledger_account": LedgerAccount.objects.get(account_number=100001),
                "amount": self.loan_amount,
            },
        )

        # create credit loan product
        TransactionEntry.objects.update_or_create(
            transaction=transaction,
            entry_type="c",
            ledger_account=self.loan_product.ledger_account,
            defaults={"amount": self.loan_amount - self.interest_amount},
        )

        # create credit interest
        TransactionEntry.objects.update_or_create(
            transaction=transaction,
            entry_type="c",
            ledger_account=self.terms.ledger_account,
            defaults={"amount": self.interest_amount},
        )

    def save(self, *args, **kwargs):
        if not self.loan_number:  # check if the instance is being created
            self.loan_number = str(uuid.uuid4().hex)[:12].upper()

        if self.status == "pending":
            self.loan_terms = self.terms.terms
            self.interest_rate = self.terms.interest_rate  # insert interest_rate
            interest_rate = self.interest_rate / 100

            # calculate monthly payment
            self.monthly_payment = calculate_loan_payment(
                interest_rate, self.loan_terms, self.loan_amount
            )  

        if self.status == "approved":  # loan approval
            self.approval_date = datetime.now()

        if self.status == "released":  # loan released
            self.release_date = datetime.now()
            self.maturity_date = self.release_date + relativedelta(
                months=self.terms.terms
            )
            if not self.transaction:
                self.create_update_transaction()

        if self.status == "cancelled":  # loan approval
            self.cancelled_date = datetime.now()

        if not self.interest_amount:
            interest_rate = self.interest_rate / 100
            terms = self.loan_terms
            loan_amount = self.loan_amount
            self.interest_amount = calculate_loan_interest(
                interest_rate, terms, loan_amount
            )

        super().save(*args, **kwargs)

    @classmethod
    def update_loan_status(cls, loan, status, fully_paid_date):
        try:
            print("update status")
            if status in cls.LoanStatus:
                loan.status = status
                loan.fully_paid_date = fully_paid_date
                loan.save()
            else:
                print("Invalid Status")
        except cls.DoesNotExist:
            print("Loan not found")

    def __str__(self):
        return f"{self.client} - {str(self.loan_number)}"


class LoanAmortization(TimeStampedModel):
    loan = models.ForeignKey(Loan, on_delete=models.CASCADE)
    term = models.IntegerField(null=True, blank=False)
    maturity_date = models.DateField(null=True, blank=True)
    principal_amount = models.DecimalField(max_digits=10, decimal_places=2)
    interest_amount = models.DecimalField(max_digits=10, decimal_places=2)
    total = models.DecimalField(max_digits=10, decimal_places=2)
    running_balance = models.DecimalField(max_digits=10, null=True, decimal_places=2)
    fully_paid = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.loan.client} - {self.loan.loan_number} - {self.maturity_date}"


class Payment(TimeStampedModel):
    class PaymentMethod(models.TextChoices):
        cash = (
            "cash",
            "Cash",
        )

    transaction = models.OneToOneField(
        Transaction, null=True, blank=True, on_delete=models.CASCADE
    )
    loan = models.ForeignKey(Loan, on_delete=models.CASCADE)
    payment_method = models.CharField(
        max_length=20, choices=PaymentMethod.choices, default=PaymentMethod.cash
    )
    payment_ref = models.CharField(max_length=15, editable=False, unique=True)
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    description = models.TextField(max_length=50, null=True, blank=True)
    payment_date = models.DateTimeField(null=True, auto_now_add=True)

    def calculate_amortization_schedule(self):
        now = datetime.now()

apps/dashboard/forms.py
from django import forms
from django.db.models import Sum
from apps.clients.models import Client
from apps.loans.models import Loan, Payment, LoanAmortization
from datetime import datetime
from apps.loans.services import get_total_loan_release, get_total_payment, get_total_due_amount
from dynamic_forms import DynamicField, DynamicFormMixin


currency_sign = '₱'

class TotalBorrowersWidget(forms.Widget):
    def render(self, name, value, attrs=None, renderer=None):
        total = Client.objects.count()
        return str(total)


class TotalLoanReleaseWidget(forms.Widget):
    def render(self, name, value, attrs=None, renderer=None):
        total = get_total_loan_release()
        return f'{currency_sign}{total}'
    

class TotalPaymentWidget(forms.Widget):
    def render(self, name, value, attrs=None, renderer=None):
        total = get_total_payment()
        return f'{currency_sign}{total}'
    

class TotalDueAmountWidget(forms.Widget):
    def render(self, name, value, attrs=None, renderer=None):
        now = datetime.now()
        total_due_amount = get_total_due_amount(now)
        total_payment = get_total_payment()
        total = total_due_amount - total_payment
        return f'{currency_sign}{total}'


class YearSelectWidget(forms.Select):
    def __init__(self, attrs=None):
        start_year = datetime.now().year #get_year_min()
        max_year = datetime.now().year + 1 #get_year_max() + 1

        years = [year for year in range(start_year, max_year)]  # Adjust the range of years as needed
        choices = [(year, str(year)) for year in years]
        super().__init__(attrs, choices)


class DashboardForm(forms.Form):
    year = forms.ChoiceField(choices=[], widget=YearSelectWidget, initial=datetime.now().year)
    total_borrowers = forms.CharField(widget=TotalBorrowersWidget(), disabled=True)
    total_loan_release = forms.CharField(widget=TotalLoanReleaseWidget(), disabled=True)
    total_payment = forms.CharField(widget=TotalPaymentWidget(), disabled=True)
    total_due_amount = forms.CharField(widget=TotalDueAmountWidget(), disabled=True)
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['year'].choices = datetime.now().year # self.get_year_choices()

    def get_year_choices(self):
        start_year = datetime.now().year #get_year_min()
        max_year = datetime.now().year + 1 #get_year_max() + 1
        years = [(year, str(year)) for year in range(start_year, max_year)]  # Adjust the range of years as needed
        return years

apps/dashboard/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.list import ListView
from .forms import DashboardForm
from django.http import JsonResponse
from apps.loans.services import get_total_loan_release, get_total_payment, get_total_due_amount, get_loan_release_per_year, get_year_min
from datetime import datetime
from decimal import Decimal
from apps.transactions.models import Transaction, TransactionEntry
from apps.loans.models import Loan, Payment
from apps.clients.models import Client

currency_sign = '₱'

# Create your views here.
class DashboardView(LoginRequiredMixin, ListView):
    login_url = "users:login"
    
    template_name = "dashboard/dashboard.html"

    redirect_field_name = "dashboard:dashboard"
    form_class = DashboardForm

    def get_queryset(self):
        return None
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = self.form_class()  # Pass an instance of your form to the context
        return context
    

def donut_chart_statistic(request):
    print('get stat donut')
    now = datetime.now()
    total_loan_release = get_total_loan_release()
    total_payment = get_total_payment()
    due_amount = get_total_due_amount(now)
    total_due_amount = due_amount - total_payment

    labels = ["Loan Releases", "Payment", "Due Amount"]
    data = [total_loan_release, total_payment, total_due_amount]
    
    chart_data = {
        'labels': labels,
        'data': data 
    }
    return JsonResponse(chart_data)


def bar_chart_statistic(request):
    print("get bar chart")
    # year = 2024
    year = request.GET.get("year")
    if year is None:
        year = get_year_min()
    print(year)
    loan_releases = get_loan_release_per_year(year)

    labels = [
        "Jan",
        "Feb",
        "Mar",
        "Apr",
        "May",
        "Jun",
        "Jul",
        "Aug",
        "Sep",
        "Oct",
        "Nov",
        "Dec",
    ]

    data = [0] * len(labels)

    for loan_release in loan_releases:
        month_index = loan_release['month'] - 1
        data[month_index] = float(loan_release['total_amount'])

    chart_data = {
        'labels': labels,
        'data': data
    }

    return JsonResponse(chart_data)


def recent_loan_activity(request):
    loans = Loan.objects.all().order_by("-updated_at")[:5]
    context = {"loans": loans, "currency_sign": currency_sign}

    return render(request, "dashboard/partials/recent-loan.html", context)


def recent_payment_activity(request):
    payments = Payment.objects.all().order_by("-updated_at")[:5]
    context = {"payments": payments, "currency_sign": currency_sign}

    return render(request, "dashboard/partials/recent-payment.html", context)


def recent_client(request):
    clients = Client.objects.all().order_by("-updated_at")[:5]
    context = {"clients": clients}

    return render(request, "dashboard/partials/recent-client.html", context)

templates/dashboard/partials/recent-activity.html
<div class="space-y-16 py-16 xl:space-y-20">
    <!-- Recent activity table -->
    <div id="recent-loan" hx-get="{% url 'dashboard:recent-loan' %}" hx-trigger="revealed" hx-target="this">
    </div>

    <!-- Recent payment -->
    <div id="recent-payment" hx-get="{% url 'dashboard:recent-payment' %}" hx-trigger="revealed" hx-target="this">
    </div>

    <!-- Recent client list-->
    <div id="recent-client" hx-get="{% url 'dashboard:recent-client' %}" hx-trigger="revealed" hx-target="this">
    </div>
</div>

templates/dashboard/partials/recent-client.html
<div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
    <h2 class="mx-auto max-w-2xl text-base font-semibold leading-6 text-gray-900 lg:mx-0 lg:max-w-none">Recent Client</h2>
  </div>
  <div class="mt-1 overflow-hidden border-t border-gray-100">
    <div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
      <div class="mx-auto max-w-2xl lg:mx-0 lg:max-w-none">
        <table class="w-full text-left">
          <thead class="sr-only">
            <tr>
              <th class="hidden sm:table-cell">Client</th>
              <th>More details</th>
            </tr>
          </thead>
          <tbody>
            <!-- <tr class="text-sm leading-6 text-gray-900">
              <th scope="colgroup" colspan="3" class="relative isolate py-2 font-semibold">
                <div class="absolute inset-y-0 right-full -z-10 w-screen border-b border-gray-200 bg-gray-50"></div>
                <div class="absolute inset-y-0 left-0 -z-10 w-screen border-b border-gray-200 bg-gray-50"></div>
              </th>
            </tr> -->
            {% for client in clients %}
            <tr>
              <td class="hidden py-5 pr-6 sm:table-cell">
                <div class="text-sm leading-6 text-gray-900">{{ client.full_name }}</div>
                <div class="mt-1 text-xs leading-5 text-gray-500">{{ client.occupation }}</div>
              </td>
              <td class="py-5 text-right">
                <div class="flex justify-end">
                  <a href="#" class="text-sm font-medium leading-6 text-indigo-600 hover:text-indigo-500">View</a>
                </div>
                <div class="mt-1 text-xs leading-5 text-gray-500">Borrower ID <span class="text-gray-900">{{ client.pk }}</span></div>
              </td>
            </tr>
            {% endfor%}
            
          </tbody>
        </table>
      </div>
    </div>
  </div>

templates/dashboard/partials/recent-loan.html
<div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
    <h2 class="mx-auto max-w-2xl text-base font-semibold leading-6 text-gray-900 lg:mx-0 lg:max-w-none">Recent Loan activity</h2>
</div>
<div class="mt-1 overflow-hidden border-t border-gray-100">
    <div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
    <div class="mx-auto max-w-2xl lg:mx-0 lg:max-w-none">
        <table class="w-full text-left">
        <thead class="sr-only">
            <tr>
            <th>Amount</th>
            <th class="hidden sm:table-cell">Client</th>
            <th>More details</th>
            </tr>
        </thead>
        <tbody>
            <!-- <tr class="text-sm leading-6 text-gray-900">
            <th scope="colgroup" colspan="3" class="relative isolate py-2 font-semibold">
                <div class="absolute inset-y-0 right-full -z-10 w-screen border-b border-gray-200 bg-gray-50"></div>
                <div class="absolute inset-y-0 left-0 -z-10 w-screen border-b border-gray-200 bg-gray-50"></div>
            </th>
            </tr> -->
            {% for loan in loans %}
            <tr>
                <td class="relative py-5 pr-6">
                    <div class="flex gap-x-6">
                    <div class="flex-auto">
                        <div class="flex items-start gap-x-3">
                        <div class="text-sm font-medium leading-6 text-gray-900">{{ currency_sign }}{{ loan.loan_amount }}</div>
                        <div class="rounded-md py-1 px-2 text-xs font-medium ring-1 ring-inset text-green-700 bg-green-50 ring-green-600/20">{{ loan.get_status_display }}</div>
                        </div>
                        <div class="mt-1 text-xs leading-5 text-gray-500">{{ currency_sign }}{{ loan.interest_amount }} Interest</div>
                    </div>
                    </div>
                    <div class="absolute bottom-0 right-full h-px w-screen bg-gray-100"></div>
                    <div class="absolute bottom-0 left-0 h-px w-screen bg-gray-100"></div>
                </td>
                <td class="hidden py-5 pr-6 sm:table-cell">
                    <div class="text-sm leading-6 text-gray-900">{{ loan.client }}</div>
                    <div class="mt-1 text-xs leading-5 text-gray-500">{{ loan.client.occupation }}</div>
                </td>
                <td class="py-5 text-right">
                    <div class="flex justify-end">
                    <a href="#" class="text-sm font-medium leading-6 text-indigo-600 hover:text-indigo-500">View<span class="hidden sm:inline"> transaction</span><span class="sr-only">, invoice #00012, Reform</span></a>
                    </div>
                    <div class="mt-1 text-xs leading-5 text-black-500">Loan No. <span class="text-gray-900">{{ loan.loan_number }}</span></div>
                </td>
            </tr>
            {% endfor %}
        </tbody>
        </table>
    </div>
    </div>
</div>

templates/dashboard/partials/recent-payment.html
<div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
    <h2 class="mx-auto max-w-2xl text-base font-semibold leading-6 text-gray-900 lg:mx-0 lg:max-w-none">Recent Payment activity</h2>
</div>
<div class="mt-1 overflow-hidden border-t border-gray-100">
    <div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
    <div class="mx-auto max-w-2xl lg:mx-0 lg:max-w-none">
        <table class="w-full text-left">
        <thead class="sr-only">
            <tr>
            <th>Amount</th>
            <th class="hidden sm:table-cell">Client</th>
            <th>More details</th>
            </tr>
        </thead>
        <tbody>
            <!-- <tr class="text-sm leading-6 text-gray-900">
            <th scope="colgroup" colspan="3" class="relative isolate py-2 font-semibold">
                <div class="absolute inset-y-0 right-full -z-10 w-screen border-b border-gray-200 bg-gray-50"></div>
                <div class="absolute inset-y-0 left-0 -z-10 w-screen border-b border-gray-200 bg-gray-50"></div>
            </th>
            </tr> -->
            {% for payment in payments %}
            <tr>
                <td class="relative py-5 pr-6">
                    <div class="flex gap-x-6">
                    <div class="flex-auto">
                        <div class="flex items-start gap-x-3">
                        <div class="text-sm font-medium leading-6 text-gray-900">{{ currency_sign }}{{ payment.amount }}</div>
                        <div class="rounded-md py-1 px-2 text-xs font-medium ring-1 ring-inset text-green-700 bg-green-50 ring-green-600/20">{{ payment.get_payment_method_display }}</div>
                        </div>
                        <div class="mt-1 text-xs leading-5 text-gray-500">{{ payment.payment_date }} Payment Date</div>
                    </div>
                    </div>
                    <div class="absolute bottom-0 right-full h-px w-screen bg-gray-100"></div>
                    <div class="absolute bottom-0 left-0 h-px w-screen bg-gray-100"></div>
                </td>
                <td class="hidden py-5 pr-6 sm:table-cell">
                    <div class="text-sm leading-6 text-gray-900">{{ payment.loan.client }}</div>
                    <div class="mt-1 text-xs leading-5 text-gray-500">{{ payment.loan.client.occupation }}</div>
                </td>
                <td class="py-5 text-right">
                    <div class="flex justify-end">
                    <a href="#" class="text-sm font-medium leading-6 text-indigo-600 hover:text-indigo-500">View<span class="hidden sm:inline"> transaction</span><span class="sr-only">, invoice #00012, Reform</span></a>
                    </div>
                    <div class="mt-1 text-xs leading-5 text-black-500">Reference No. <span class="text-gray-900">{{ payment.payment_ref }}</span></div>
                </td>
            </tr>
            {% endfor %}
        </tbody>
        </table>
    </div>
    </div>
</div>