apps/clients/urls.py
from django.urls import path
from .views import (
    ClientInformation,
    AddClientForm,
    ViewClientForm,
    UpdateClientForm,
    search_client,
    client_page,
    add_client,
    update_client,
)

app_name = "clients"

urlpatterns = [
    path("clients/", ClientInformation.as_view(), name="clients"),
    path("add-client-form/", AddClientForm.as_view(), name="add-client-form"),
    path("view-client/<int:pk>/", ViewClientForm.as_view(), name="view-client"),
    path(
        "update-client-form/<int:pk>/",
        UpdateClientForm.as_view(),
        name="update-client-form",
    ),
]

htmx_urlpatterns = [
    path("search-client/", search_client, name="search-client"),
    path("client-page/<int:page>", client_page, name="page-client"),
    path("add-client/", add_client, name="add-client"),
    path("update-client/<int:pk>/", update_client, name="update-client"),
    
]

urlpatterns += htmx_urlpatterns

config/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import include, path, re_path
from django.views.static import serve
from drf_spectacular.views import (
    SpectacularAPIView,
    SpectacularRedocView,
    SpectacularSwaggerView,
)

schema_urls = [
    # YOUR PATTERNS
    path("api/v1/schema/", SpectacularAPIView.as_view(), name="schema"),
    # Optional UI:
    path(
        "api/v1/schema/swagger/",
        SpectacularSwaggerView.as_view(url_name="schema"),
        name="swagger",
    ),
    path(
        "api/v1/schema/redoc/",
        SpectacularRedocView.as_view(url_name="schema"),
        name="redoc",
    ),
]

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("apps.common.urls")),
    path("", include("apps.dashboard.urls")),
    path("", include("apps.users.urls")),
    path("", include("apps.clients.urls")),
    path("", include("apps.loans.urls")),
    path("", include("apps.transactions.urls")),
    path("", include("apps.ledger_accounts.urls")),
    path("", include("apps.collectors.urls")),
    re_path(r"^media/(?P<path>.*)$", serve, {"document_root": settings.MEDIA_ROOT}),
]

urlpatterns += schema_urls
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [
        path("__debug__/", include(debug_toolbar.urls)),
    ]

apps/clients/models.py
from django.db import models


# Create your models here.
class TimeStampedModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class Client(TimeStampedModel):
    class Gender(models.TextChoices):
        MALE = "male", "Male"
        Female = "female", "Female"

    class Country(models.TextChoices):
        PHILIPPINES = "philippines", "Philippines"

    first_name = models.CharField(max_length=150)
    middle_name = models.CharField(max_length=150)
    last_name = models.CharField(max_length=150)
    email = models.CharField(max_length=150)
    birth = models.DateField(blank=False)
    gender = models.CharField(max_length=50, choices=Gender.choices)
    country = models.CharField(max_length=100, choices=Country.choices)
    address = models.CharField(max_length=150)
    city = models.CharField(max_length=50)
    state = models.CharField(max_length=50)
    zip_code = models.CharField(max_length=10)
    contact_no = models.CharField(max_length=50)
    occupation = models.CharField(max_length=100)
    photo = models.ImageField(upload_to="client_photos", null=True, blank=True)
    is_active = models.BooleanField(default=True)

    @property
    def display_display_address(self):
        return (
            f"{self.address}, {self.city},  {self.state} {self.zip_code} {self.country}"
        )

    @property
    def full_name(self):
        return f"{self.first_name} {self.middle_name} {self.last_name}"

    def __str__(self):
        return f"{self.first_name} {self.middle_name} {self.last_name}"

apps/clients/forms.py
from django import forms
from apps.clients.models import Client


class DateInput(forms.DateInput):
    input_type = "date"


class ClientForm(forms.ModelForm):
    photo = forms.ImageField(widget=forms.FileInput)

    class Meta:
        model = Client
        fields = (
            "photo",
            "first_name",
            "middle_name",
            "last_name",
            "email",
            "birth",
            "gender",
            "country",
            "address",
            "city",
            "state",
            "zip_code",
            "contact_no",
            "occupation",
        )

        widgets = {
            "birth": DateInput,
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        # # Access choices for the 'gender' field
        # gender_choices = models.Client.Gender.choices
        country_choices = Client.Country.choices

        # Update the choices for the 'gender' field
        # self.fields['gender'].choices = gender_choices
        self.fields["country"].choices = country_choices

apps/clients/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.list import ListView
from django.conf import settings
from .models import Client
from django.db.models.functions import Concat
from django.db.models import Value
from django.core.paginator import Paginator
from django.views.generic import FormView
from .forms import ClientForm
from django.contrib import messages
from django.shortcuts import get_object_or_404, render


# Create your views here.
class ClientInformation(LoginRequiredMixin, ListView):
    template_name = "client/clients.html"
    model = Client

    paginate_by = settings.PAGINATE_BY  # set number of records per page


class ViewClientForm(LoginRequiredMixin, FormView):
    def get(self, request, pk):
        print("view client details")
        client = Client.objects.get(pk=pk)
        form = ClientForm(request.POST or None, instance=client)

        context = {
            "client": client,
            "forms": form,
        }

        return render(request, "client/partials/client-view.html", context)


class AddClientForm(LoginRequiredMixin, ListView):
    def get(self, request):
        print("load client add page")
        form = ClientForm(request.POST or None)
        client = {"photo": None}
        context = {"client": client, "forms": form}
        return render(request, "client/partials/client-add-form.html", context)


class ViewClientForm(LoginRequiredMixin, FormView):
    def get(self, request, pk):
        print("view client details")
        client = Client.objects.get(pk=pk)
        form = ClientForm(request.POST or None, instance=client)

        context = {
            "client": client,
            "forms": form,
        }

        return render(request, "client/partials/client-view.html", context)


class UpdateClientForm(LoginRequiredMixin, FormView):
    def get(self, request, pk):
        print("load client update page")
        current_record = Client.objects.get(id=pk)
        form = ClientForm(request.POST or None, instance=current_record)

        client = get_object_or_404(Client, pk=pk)
        context = {"client": client, "forms": form}

        return render(request, "client/partials/client-update-form.html", context)


def search_client(request):
    print("search")
    search_text = request.POST.get("search-client")
    annotated_objects = Client.objects.annotate(
        fullname=Concat(
            'first_name',
            Value(' '),  # Separator
            'middle_name',
            Value(' '),  # Separator
            'last_name'
        )
    )
    
    clients = annotated_objects.filter(fullname__icontains=search_text)

    total_records = clients.count()  # count total records

    context = {"clients": clients, "total_records": total_records}
    return render(request, "client/partials/combobox-client-search.html", context)


def client_page(request, page):
    print("get page")
    search_text = request.POST.get("search-client")
    print(search_text)
    annotated_objects = Client.objects.annotate(
        fullname=Concat(
            "first_name",
            Value(" "),  # Separator
            "middle_name",
            Value(" "),  # Separator
            "last_name",
        )
    )

    clients = annotated_objects.filter(fullname__icontains=search_text).order_by(
        "-created_at"
    )

    # setup pagination
    p = Paginator(clients, settings.PAGINATE_BY)
    clients = p.get_page(page)

    total_records = p.count  # count total records

    context = {"clients": clients, "total_records": total_records}
    return render(request, "client/partials/client-list-elements.html", context)


def add_client(request):
    print("add client")
    form = ClientForm(request.POST, request.FILES or None)
    if form.is_valid():
        form.save()
        clients = Client.objects.all()
        context = {"clients": clients}
        messages.success(request, "Record added...")
        return render(request, "client/partials/client-list.html", context)
    form = ClientForm(request.POST or None)
    context = {"forms": form}
    return render(request, "client/partials/client-fields.html", context)


def update_client(request, pk):
    print("update client")
    current_record = Client.objects.get(id=pk)
    form = ClientForm(request.POST, request.FILES or None, instance=current_record)
    if form.is_valid():
        form.save()
        # clients = Client.objects.all()
        context = {"forms": form, "client": current_record}
        messages.success(request, "Record updated...")
        return render(request, "client/partials/client-view-details.html", context)
    form = ClientForm(request.POST or None, instance=current_record)
    context = {"forms": form, "client": current_record}
    return render(request, "client/partials/client-fields.html", context)

templates/client/partials/client-add-form.html
<form hx-encoding="multipart/form-data"
        hx-post="{% url 'clients:add-client' %}"      
        hx-target="#client"
        >
    {% csrf_token %}
    {% include 'client/partials/client-fields.html' %}
</form>

templates/client/partials/client-button-page.html
<nav class="flex items-center justify-between bg-white py-3" aria-label="Pagination">
    <div class="pagination gap-x-3">
        {% if clients.has_previous %}
            <button hx-post="{% url 'clients:page-client' 1 %}"
                    hx-target="#client-list"
                    class="relative inline-flex items-center rounded-md bg-white px-3 py-2 text-sm font-semibold text-gray-900 ring-1 ring-inset ring-gray-300 hover:bg-gray-50 focus-visible:outline-offset-0">
                first
            </button>
        {% else %}
            <span disable
                    class="relative inline-flex items-center rounded-md bg-gray px-3 py-2 text-sm font-semibold text-gray-900 ring-1 ring-inset ring-gray-300 hover:bg-gray-50 focus-visible:outline-offset-0">
                first
            </span>
        {% endif %}

        {% if clients.has_previous %}
            <button hx-post="{% url 'clients:page-client'  clients.previous_page_number  %}"
                    hx-target="#client-list"
                    class="relative inline-flex items-center rounded-md bg-white px-3 py-2 text-sm font-semibold text-gray-900 ring-1 ring-inset ring-gray-300 hover:bg-gray-50 focus-visible:outline-offset-0">
                previous
            </button>
        {% else %}
            <span disabled
                    class="relative inline-flex items-center rounded-md bg-white px-3 py-2 text-sm font-semibold text-gray-900 ring-1 ring-inset ring-gray-300 hover:bg-gray-50 focus-visible:outline-offset-0">
                previous
            </span>
        {% endif %}

        {% if clients.has_next %}
            <button hx-post="{% url 'clients:page-client'  clients.next_page_number  %}"
                    hx-target="#client-list"
                    class="relative inline-flex items-center rounded-md bg-white px-3 py-2 text-sm font-semibold text-gray-900 ring-1 ring-inset ring-gray-300 hover:bg-gray-50 focus-visible:outline-offset-0">
                next
            </button>

        {% else %}
            <span disabled
                    class="relative inline-flex items-center rounded-md bg-white px-3 py-2 text-sm font-semibold text-gray-900 ring-1 ring-inset ring-gray-300 hover:bg-gray-50 focus-visible:outline-offset-0">
                next
            </span>
        {% endif %}

        {% if clients.has_next %}
            <button hx-post="{% url 'clients:page-client'  clients.paginator.num_pages  %}"
                    hx-target="#client-list"
                    class="relative inline-flex items-center rounded-md bg-white px-3 py-2 text-sm font-semibold text-gray-900 ring-1 ring-inset ring-gray-300 hover:bg-gray-50 focus-visible:outline-offset-0">
                last
            </button>
        {% else %}
            <span disabled
                    class="relative inline-flex items-center rounded-md bg-white px-3 py-2 text-sm font-semibold text-gray-900 ring-1 ring-inset ring-gray-300 hover:bg-gray-50 focus-visible:outline-offset-0">
                last
            </span>
        {% endif %}
    </div>

    <div class="flex flex-1 justify-between sm:justify-end mr-4">
        <p class="text-sm text-gray-700">
        <span class="font-medium">{{ total_records }}</span>
        records found
        </p>
    </div>
</nav>

<div class="hidden sm:block">
    <span class="current">
      Page {{ clients.number }} of {{ clients.paginator.num_pages }}.
    </span>
</div>

templates/client/partials/client-fields.html
{% load widget_tweaks %}

<div class="grid grid-cols-1 border-b border-gray-900/10 pb-12 md:grid-cols-2 flex items-center justify-end gap-x-6 border-t border-gray-900/10  py-4 bg-gray-50 text-white py-4 px-6 sticky top-0 z-50">
  <div>
    <h2 class="text-base font-semibold leading-7 text-gray-900">
      {% if forms.first_name.value %}
        {{ client.full_name }}
      {% else %}
        New Client
      {% endif %}
    </h2>
  </div>
  
  <div class="text-right inline-flow">
    <span class="p-4">
      <a href="{% url 'clients:clients' %}" class="text-sm font-semibold leading-6 text-gray-900">Cancel</a>
    </span>
    <button type="submit"
            class="rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600"
    >Save</button>
  </div>
 
</div>

<div class="grid grid-cols-1 gap-y-10 border-b border-gray-900/10 pb-12 md:grid-cols-4">
  <div class="grid max-w-2xl grid-cols-1 gap-x-6 gap-y-8 sm:grid-cols-6 md:col-span-2 pt-5">
    <div class="col-span-full">
      {% include 'client/partials/image-upload.html' %}
    </div>

      <div class="sm:col-span-3">
        <label for="first_name" class="block text-sm font-medium leading-6 text-gray-900">First name</label>
        <div class="mt-2">
          {% render_field forms.first_name class="px-2 block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6" %}
        </div>
      </div>

      <div class="sm:col-span-3">
        <label for="last_name" class="block text-sm font-medium leading-6 text-gray-900">Last name</label>
        <div class="mt-2">
          {% render_field forms.last_name class="px-2 block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6" %}
        </div>
      </div>

      <div class="sm:col-span-3">
        <label for="middle_name" class="block text-sm font-medium leading-6 text-gray-900">Middle name</label>
        <div class="mt-2">
          {% render_field forms.middle_name class="px-2 block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6" %}
        </div>
      </div>

      <div class="sm:col-span-4">
        <label for="email" class="block text-sm font-medium leading-6 text-gray-900">Email address</label>
        <div class="mt-2">
          {% render_field forms.email pattern="[^\s@]+@[^\s@]+\.[^\s@]+" class="px-2 block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6" %}
        </div>
      </div>

      <div class="sm:col-span-4">
        <label for="birth" class="block text-sm font-medium leading-6 text-gray-900">Birthday</label>
        <div class="mt-2">
          {% render_field forms.birth class="px-2 block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6"%}
        </div>
      </div>

      <div class="sm:col-span-4">
        <label for="gender" class="block text-sm font-medium leading-6 text-gray-900">Gender</label>
        <div class="mt-2">
          {%  render_field forms.gender class="px-2 bg-white block rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:max-w-xs sm:text-sm sm:leading-6" %}
        </div>
      </div>

      <div class="sm:col-span-4">
        <label for="country" class="block text-sm font-medium leading-6 text-gray-900">Country</label>
        <div class="mt-2">
          {% render_field forms.country class="px-2 bg-white block rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:max-w-xs sm:text-sm sm:leading-6" %}
        </div>
      </div>

      <div class="col-span-full">
        <label for="address" class="block text-sm font-medium leading-6 text-gray-900">Street address</label>
        <div class="mt-2">
            {% render_field forms.address class="px-2 block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6" %}
        </div>
      </div>

      <div class="sm:col-span-2 sm:col-start-1">
        <label for="city" class="block text-sm font-medium leading-6 text-gray-900">City</label>
        <div class="mt-2">
          {% render_field forms.city class="px-2 block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6" %}
        </div>
      </div>

      <div class="sm:col-span-2">
        <label for="state" class="block text-sm font-medium leading-6 text-gray-900">State / Province</label>
        <div class="mt-2">
          {% render_field forms.state class="px-2 block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6" %}
        </div>
      </div>

      <div class="sm:col-span-2">
        <label for="zip_code" class="block text-sm font-medium leading-6 text-gray-900">ZIP / Postal code</label>
        <div class="mt-2">
          {% render_field forms.zip_code class="px-2 block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6" %}
        </div>
      </div>

      <div class="sm:col-span-4">
        <label for="contact_no" class="block text-sm font-medium leading-6 text-gray-900">Contact No.</label>
        <div class="mt-2">
          {% render_field forms.contact_no class="px-2 block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6" %}
        </div>
      </div>

      <div class="sm:col-span-4">
        <label for="occupation" class="block text-sm font-medium leading-6 text-gray-900">Occupation</label>
        <div class="mt-2">
          {% render_field forms.occupation class="px-2 block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6" %}
        </div>
      </div>
  </div>
</div>

templates/client/partials/client-list-elements.html
{% include 'client/partials/client-button-page.html' %}

<div class="mt-4 flow-root">
    <div class="-mx-4 -my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
      <div class="inline-block min-w-full py-2 align-middle sm:px-6 lg:px-8">
        <div id="no-more-tables" class="overflow-hidden shadow ring-1 ring-black ring-opacity-5 sm:rounded-lg">
          <table class="min-w-full divide-y divide-gray-300">
              <thead class="bg-gray-50">
                <tr>
                  <th scope="col" class="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-6">Name</th>
                  <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Email</th>
                  <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Date of Birth</th>
                  <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Gender</th>
                  <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Country</th>
                  <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Contact Number</th>
                  <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Occupation</th>
                  <th scope="col" class="relative py-3.5 pl-3 pr-4 sm:pr-6">
                  <span class="sr-only">Edit</span>
                  </th>
                </tr>
              </thead>
            <tbody class="divide-y divide-gray-200 bg-white" >
               
            {% for client in clients %}
            <tr>
                <td data-title="Name" class="whitespace-nowrap py-4 pl-4 pr-3 text-sm font-medium text-gray-900 sm:pl-6">{{ client.full_name }}</td>
                <td data-title="Email" class="whitespace-nowrap px-3 py-4 text-sm text-gray-500">{{ client.email }}</td>
                <td data-title="Date of Birth" class="whitespace-nowrap px-3 py-4 text-sm text-gray-500">{{ client.birth }}</td>
                <td data-title="Gender" class="whitespace-nowrap px-3 py-4 text-sm text-gray-500">{{ client.get_gender_display }}</td>
                <td data-title="Country" class="whitespace-nowrap px-3 py-4 text-sm text-gray-500">{{ client.get_country_display }}</td>
                <td data-title="Contact Number" class="whitespace-nowrap px-3 py-4 text-sm text-gray-500">{{ client.contact_no }}</td>
                <td data-title="Occupation" class="whitespace-nowrap px-3 py-4 text-sm text-gray-500">{{ client.occupation }}</td>
                <td class="relative whitespace-nowrap py-4 pl-3 pr-4 text-right text-sm font-medium sm:pr-6">
                    <a href="{% url 'clients:view-client' client.pk %}" class="text-indigo-600 hover:text-indigo-900">View</a>
                </td>
            </tr>
            {% endfor %}
            
            </tbody>
           
          </table>
          {% if not clients %}
            <p class="p-2 text-center">no records found</p>
          {% endif %}
        </div>
      </div>
    </div>
</div>

templates/client/partials/client-view-details.html
{% load static %}
{% load widget_tweaks %}

{% if messages %}
{% for message in messages %}
    <div class="alert alert-warning alert-dismissible fade show" role="alert">{{ message }}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
{% endfor %}
{% endif %}

<div class="grid grid-cols-1 border-b border-gray-900/10 pb-12 md:grid-cols-2 flex items-center justify-end gap-x-6 border-t border-gray-900/10  py-3 bg-gray-50 text-white py-4 px-6 sticky top-0 z-50 mb-5">
  <div>
    <h2 class="text-base font-semibold leading-7 text-gray-900">{{ client.full_name }}</h2>
  </div>
  
  <div class="text-right inline-flow">
    <span class="p-4">
      <a href="{% url 'clients:clients' %}" class="text-sm font-semibold leading-6 text-gray-900">Back</a>
    </span>
    <button hx-get="{% url 'clients:update-client-form' client.pk %}" hx-target="#client-view"
            type="button"
            class="rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600"
    >Update</button>
  </div>
</div>

<div class="overflow-hidden bg-white shadow sm:rounded-lg">
    <div class="px-4 py-6 sm:px-6">
      <h3 class="text-base font-semibold leading-7 text-gray-900">Client's Information</h3>
      <p class="mt-1 max-w-2xl text-sm leading-6 text-gray-500">Personal details.</p>
    </div>
    <div class="border-t border-gray-100">
      <dl class="divide-y divide-gray-100">
        <div class="px-4 py-6 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
            <dt class="text-sm font-semibold text-gray-900">Image</dt>
            <div class="mt-2 block items-center gap-x-3">
                <img id="imagePreview"
                    {% if client.photo %}
                        src="{{ client.photo.url }}"
                    {% else %}
                        src="{% static 'images/default_image.png' %}"
                    {% endif %}
                    alt="Image Preview" style="max-width: 150px; max-height: 150px;">
            </div>
          </div>
        <div class="px-4 py-6 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
          <dt class="text-sm font-semibold text-gray-900">Full name</dt>
          <dd class="mt-1 text-sm leading-6 text-gray-700 sm:col-span-2 sm:mt-0">{{ client.full_name }}</dd>
        </div>
        <div class="px-4 py-6 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
          <dt class="text-sm font-semibold text-gray-900">Email</dt>
          <dd class="mt-1 text-sm leading-6 text-gray-700 sm:col-span-2 sm:mt-0">{{ client.email }}</dd>
        </div>
        <div class="px-4 py-6 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
          <dt class="text-sm font-semibold text-gray-900">Birhtday</dt>
          <dd class="mt-1 text-sm leading-6 text-gray-700 sm:col-span-2 sm:mt-0">{{ client.birth }}</dd>
        </div>
        <div class="px-4 py-6 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
          <dt class="text-sm font-semibold text-gray-900">Gender</dt>
          <dd class="mt-1 text-sm leading-6 text-gray-700 sm:col-span-2 sm:mt-0">{{ client.get_gender_display }}</dd>
        </div>
        <div class="px-4 py-6 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
            <dt class="text-sm font-semibold text-gray-900">Address</dt>
            <dd class="mt-1 text-sm leading-6 text-gray-700 sm:col-span-2 sm:mt-0">{{ client.display_display_address }}</dd>
        </div>
        <div class="px-4 py-6 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
            <dt class="text-sm font-semibold text-gray-900">Contact No.</dt>
            <dd class="mt-1 text-sm leading-6 text-gray-700 sm:col-span-2 sm:mt-0">{{ client.contact_no }}</dd>
        </div>
        <div class="px-4 py-6 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
            <dt class="text-sm font-semibold text-gray-900">Occupation</dt>
            <dd class="mt-1 text-sm leading-6 text-gray-700 sm:col-span-2 sm:mt-0">{{ client.occupation }}</dd>
        </div>
        
        
      </dl>
    </div>
</div>